import { Request, Response } from 'express'
import { getCsrfMiddleware, generateCsrfTokenForRequest } from './csrf.util'

describe('CSRF Protection Middleware', () => {
  const secret = 'test-secret-must-be-long-enough-for-hmac'
  const middleware = getCsrfMiddleware(secret)

  let mockReq: Partial<Request>
  let mockRes: Partial<Response>
  let mockNext: jest.Mock

  beforeEach(() => {
    mockReq = {
      method: 'GET',
      cookies: {},
      headers: {},
    }
    // Set path dynamically as any
    ;(mockReq as any).path = '/api/v1/users/me'

    mockRes = {
      status: jest.fn().mockReturnThis(),
      json: jest.fn().mockReturnThis(),
      cookie: jest.fn(),
    }
    mockNext = jest.fn()
  })

  it('should bypass GET requests', () => {
    mockReq.method = 'GET'
    middleware(mockReq as Request, mockRes as Response, mockNext)
    expect(mockNext).toHaveBeenCalledWith()
    expect(mockRes.status).not.toHaveBeenCalled()
  })

  it('should bypass webhook POST requests', () => {
    mockReq.method = 'POST'
    ;(mockReq as any).path = '/api/v1/webhooks/cashfree'
    middleware(mockReq as Request, mockRes as Response, mockNext)
    expect(mockNext).toHaveBeenCalledWith()
    expect(mockRes.status).not.toHaveBeenCalled()
  })

  it('should bypass POST requests if no accessToken cookie is present', () => {
    mockReq.method = 'POST'
    ;(mockReq as any).path = '/api/v1/loads'
    mockReq.cookies = {} // No accessToken
    middleware(mockReq as Request, mockRes as Response, mockNext)
    expect(mockNext).toHaveBeenCalledWith()
    expect(mockRes.status).not.toHaveBeenCalled()
  })

  it('should block POST requests if accessToken cookie is present but no CSRF token header is sent', () => {
    mockReq.method = 'POST'
    ;(mockReq as any).path = '/api/v1/loads'
    mockReq.cookies = { accessToken: 'some-jwt-token' }

    middleware(mockReq as Request, mockRes as Response, mockNext)
    expect(mockNext).not.toHaveBeenCalled()
    expect(mockRes.status).toHaveBeenCalledWith(403)
    expect(mockRes.json).toHaveBeenCalledWith({
      statusCode: 403,
      message: 'Invalid or missing CSRF token',
      error: 'Forbidden',
    })
  })

  it('should block POST requests if accessToken cookie is present but CSRF token is invalid', () => {
    mockReq.method = 'POST'
    ;(mockReq as any).path = '/api/v1/loads'
    mockReq.cookies = { accessToken: 'some-jwt-token' }
    mockReq.headers = { 'x-csrf-token': 'invalid-token' }

    middleware(mockReq as Request, mockRes as Response, mockNext)
    expect(mockNext).not.toHaveBeenCalled()
    expect(mockRes.status).toHaveBeenCalledWith(403)
  })

  it('should accept POST requests if accessToken cookie is present and a valid CSRF token is provided', () => {
    // 1. Generate a valid token
    const genReq = {
      cookies: { accessToken: 'some-jwt-token' },
      headers: {},
    } as unknown as Request

    const genRes = {
      cookie: jest.fn(),
    } as unknown as Response

    const validToken = generateCsrfTokenForRequest(genReq, genRes, secret)

    // Check that cookie was set
    expect(genRes.cookie).toHaveBeenCalled()
    const cookieArgs = (genRes.cookie as jest.Mock).mock.calls[0]
    const cookieName = cookieArgs[0]
    const cookieVal = cookieArgs[1]

    // 2. Submit the mutating request with both the cookie and the header
    mockReq.method = 'POST'
    ;(mockReq as any).path = '/api/v1/loads'
    mockReq.cookies = {
      accessToken: 'some-jwt-token',
      [cookieName]: cookieVal, // Attach the cookie generated by generateToken
    }
    mockReq.headers = {
      'x-csrf-token': validToken, // Attach the raw token in header
    }

    middleware(mockReq as Request, mockRes as Response, mockNext)
    expect(mockNext).toHaveBeenCalledWith()
    expect(mockRes.status).not.toHaveBeenCalled()
  })
})
