-- Additive migration for the booking digital freight document chain.
--
-- Each BookingDocument row references a file already uploaded to private
-- object storage (AWS S3 / MinIO); only the object key is stored in the
-- database. Uploads/downloads are exchanged through short-lived pre-signed
-- URLs generated by the API (never stored).
--
-- The table reuses the existing "VerificationStatus" enum shared with truck
-- KYC documents so admins can verify/reject chain documents with the same
-- status vocabulary.

-- CreateEnum
CREATE TYPE "BookingDocumentStage" AS ENUM ('BOOKING', 'EWAY_BILL', 'LOADING', 'TRANSIT', 'DELIVERY', 'POD', 'BALANCE');

-- CreateTable
CREATE TABLE "booking_documents" (
    "id" TEXT NOT NULL,
    "booking_id" TEXT NOT NULL,
    "stage" "BookingDocumentStage" NOT NULL,
    "doc_number" TEXT,
    "s3_key" TEXT NOT NULL,
    "original_filename" TEXT,
    "mime_type" TEXT,
    "file_size" INTEGER,
    "signed_by" TEXT,
    "uploaded_by_id" TEXT NOT NULL,
    "verification_status" "VerificationStatus" NOT NULL DEFAULT 'Pending',
    "verified_by_id" TEXT,
    "verification_notes" TEXT,
    "verified_at" TIMESTAMP(3),
    "uploaded_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "booking_documents_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "booking_documents_booking_id_idx" ON "booking_documents"("booking_id");
CREATE INDEX "booking_documents_booking_id_stage_idx" ON "booking_documents"("booking_id", "stage");
CREATE INDEX "booking_documents_stage_idx" ON "booking_documents"("stage");
CREATE INDEX "booking_documents_uploaded_by_id_idx" ON "booking_documents"("uploaded_by_id");
CREATE INDEX "booking_documents_verification_status_idx" ON "booking_documents"("verification_status");

-- AddForeignKey
ALTER TABLE "booking_documents" ADD CONSTRAINT "booking_documents_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "booking_documents" ADD CONSTRAINT "booking_documents_uploaded_by_id_fkey" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "booking_documents" ADD CONSTRAINT "booking_documents_verified_by_id_fkey" FOREIGN KEY ("verified_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
